name: Deploy Website

on:
  push:
    branches:
      - main  # Or the branch you want to deploy from

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Upload files via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: .  # Directory to upload
        server-dir: /public_html  # Target directory on the server
